import discord
from discord import ui
from discord.ext import commands
from discord.ui import View, Button
from datetime import datetime, timedelta
from core.logs import get_logger
import secrets
import string
from mysql.connector import Error
from core.database import create_connection

logger = get_logger()

cooldowns_suport = {}

def update_key_status(user_id, code):
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        try:
            query = """UPDATE license_keys SET valid=1 WHERE code=%s;"""
            cursor.execute(query, (code,))
            connection.commit()
            logger.info(f"Status of code {code} updated successfully, verified by ({user_id}).")
        except Error as e:
            logger.info(f"Couldn't update the code {code} status: {e}")
            return False
        finally:
            cursor.close()
            connection.close()
    return False

def get_user_id_by_key(code):
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        try:
            query = """SELECT id_user FROM license_keys WHERE code = %s LIMIT 1;"""
            cursor.execute(query, (code,))
            result = cursor.fetchone()
            if result:
                return result[0]
            else:
                return None
        except Error as e:
            logger.info(f"Error while searching for user id: {e}")
            return None
        finally:
            cursor.close()
            connection.close()
    return None

def check_verification_code(user_id, input_code):
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        try:
            query = """SELECT code, time_expire FROM verification_codes WHERE id_user = %s AND valid = TRUE ORDER BY time_created DESC LIMIT 1"""
            cursor.execute(query, (user_id,))
            result = cursor.fetchone()

            if result:
                stored_code, time_expire = result
                if stored_code == input_code and datetime.utcnow() < time_expire:
                    return True
                else:
                    logger.info(f"Code expired or invalid for user {user_id}.")
        except Error as e:
            logger.info(f"Couldn't verify the code: {e}")
        finally:
            cursor.close()
            connection.close()
    return False

def insert_verification_code(user_id, code, time_expire):
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        try:
            query = """
                INSERT INTO license_keys(id_user, code, valid, time_created, time_expire)
                VALUES (%s, %s, %s, NOW(), %s)
            """
            cursor.execute(query, (user_id, code, True, time_expire))
            connection.commit()
            logger.info(f"Code {code} generated by ({user_id}).")
        except Error as e:
            logger.info(f"Couldn't insert into db: {e}")
        finally:
            cursor.close()
            connection.close()

def generate_secure_code(user_id):
    characters = string.ascii_uppercase + string.digits
    code = '-'.join(
        ''.join(secrets.choice(characters) for _ in range(4))
            for _ in range(3)
    )
    time_expire = datetime.utcnow() + timedelta(days=30)
    insert_verification_code(user_id, code, time_expire)
    return code

async def give_role(user, role_id):
    guild = user.guild
    role = discord.utils.get(guild.roles, id=role_id)
    if role:
        await user.add_roles(role)

class suportQuest(ui.Modal, title="Suport system"):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.cooldowns_suport = cooldowns_suport

    name = ui.TextInput(label='Nome', required=False, placeholder="ex: Alfredo")
    problem = ui.TextInput(label="Problema", required=True, style=discord.TextStyle.paragraph, placeholder="Descreve o teu problema...")

    async def on_submit(self, interaction: discord.Interaction):
        user_id = interaction.user.id

        if user_id in self.cooldowns_suport:
            last_click_time = self.cooldowns_suport[user_id]
            cooldown_time = timedelta(minutes=30)
            time_left = last_click_time + cooldown_time - datetime.now()
            
            if time_left > timedelta(seconds=0):
                await interaction.response.send_message(
                    f"❌ Tens de esperar {time_left.seconds // 60} minutos para enviar outro pedido de suporte.",
                    ephemeral=True
                )
                return

        # Atualiza o cooldown antes de processar
        self.cooldowns_suport[user_id] = datetime.now()
        
        problem = self.problem.value
        user_name = self.name.value if self.name.value else "Anônimo"

        try:
            channel = interaction.guild.get_channel(1356301294188363976)
            embed = discord.Embed(
                title="❗ Novo pedido de ajuda",
                color=discord.Color.orange(),
                timestamp=interaction.created_at
            )
            embed.add_field(name="User name", value=f"```{user_name}```", inline=True)
            embed.add_field(name="User id", value=f"||```{user_id}```||", inline=True)
            embed.add_field(name="Descrição do problema", value=f"```{problem[:4000]}```", inline=False)
            embed.set_footer(text="Suport system | Powered by NoLife Dev Team", icon_url="https://cdn.discordapp.com/attachments/1352771477845315685/1352791135730536548/e5b4a8673da2b6cf452368c17dad4fc5.jpg")

            view = SupportButtonView()
            await channel.send(embed=embed, view=view)
            logger.info(f"Suport request sent by ({user_id})")
            await interaction.response.send_message("📤 Pedido de suporte enviado, irás receber uma resposta na tua DM.", ephemeral=True)
            
        except Exception as e:
            logger.error(f"Error processing support request: {e}")
            await interaction.response.send_message("❌ Ocorreu um erro ao enviar o pedido de suporte!", ephemeral=True)

class verifyQuest(ui.Modal, title="License key system"):
    name = ui.TextInput(label='Nome', required=False, placeholder="Ex: User")
    code = ui.TextInput(label='Codigo de verificação', style=discord.TextStyle.short, placeholder="Verifica a tua DM para encontrar o código!", required=True, max_length=6)

    async def on_submit(self, interaction: discord.Interaction):
        user_id = interaction.user.id
        input_code = self.code.value
        user = interaction.user

        await interaction.response.defer(ephemeral=True)
        
        if check_verification_code(user_id, input_code):
            update_key_status(user_id, input_code)
            role_id = 1393321539520299009 #id da role de quem tem o servico
            await give_role(user, role_id)
            await interaction.followup.send("🎉 Key verificada com sucesso, aproveita!", ephemeral=True)
            logger.info(f"User {user_id} verified successfully!")
        else:
            await interaction.followup.send("❌ Key inválida ou expirado! Por favor tenta novamente.", ephemeral=True)

class resetQuest(ui.Modal, title="License key system"):
    name = ui.TextInput(label='Nome', required=False, placeholder="Ex: User")
    code = ui.TextInput(label='Codigo de verificação', style=discord.TextStyle.short, placeholder="Verifica a tua DM para encontrar o código!", required=True, max_length=6)

    async def on_submit(self, interaction: discord.Interaction):
        user_id = interaction.user.id
        input_code = self.code.value
        user = interaction.user

        await interaction.response.defer(ephemeral=True)
        
        if check_verification_code(user_id, input_code):
            update_key_status(user_id, input_code)
            role_id = 1393321539520299009 #id da role de quem tem o servico
            await give_role(user, role_id)
            await interaction.followup.send("🎉 Key verificada com sucesso, aproveita!", ephemeral=True)
            logger.info(f"User {user_id} verified successfully!")
        else:
            await interaction.followup.send("❌ Key inválida ou expirado! Por favor tenta novamente.", ephemeral=True)

class SupportButtonView(View):
    def __init__(self):
        super().__init__(timeout=None)

    @discord.ui.button(label="✅ Resolvido", style=discord.ButtonStyle.success, custom_id="support_resolved")
    async def resolved_callback(self, interaction: discord.Interaction, button: Button):
        embed = interaction.message.embeds[0]
        embed.title = "✅ Pedido de ajuda resolvido"
        embed.color = discord.Color.green()
        embed.add_field(name="Resolvido por", value=f"{interaction.user.mention}", inline=False)
        
        user_id = None
        user_name = None

        for field in embed.fields:
            if field.name == "User id":
                parts = field.value.split('```')
                if len(parts) >= 2:
                    user_id_str = parts[1].strip()
                    try:
                        user_id = int(user_id_str)
                    except ValueError:
                        break        
                break

        for field in embed.fields:
            if field.name == "User name":
                user_name = field.value.replace('```', '').strip()
                break

        if user_id:
            try:
                user = await interaction.client.fetch_user(user_id)
                await user.send("🎉 Seu pedido de suporte foi marcado como resolvido!\nObrigado por entrar em contato!")
            except discord.Forbidden:
                logger.error(f"Error sending dm to user {user_id} (blocked DM)")
            except discord.NotFound:
                print(f"Error sending dm to {user_id} not found")


        await interaction.message.edit(embed=embed, view=None)
        await interaction.response.send_message(f"✅ Pedido resolvido, dm enviada ao {user_name} ({user_id}) !", ephemeral=True)

def user_already_has_key(user_id):
    connection = create_connection()
    if connection:
        cursor = connection.cursor()
        try:
            query = """SELECT COUNT(*) FROM license_keys WHERE id_user = %s"""
            cursor.execute(query, (user_id,))
            result = cursor.fetchone()
            return result and result[0] > 0
        except Error as e:
            logger.info(f"Erro ao verificar chave existente: {e}")
        finally:
            cursor.close()
            connection.close()
    return False

class LicenseApprovalView(View):
    def __init__(self, code, user_id):
        super().__init__(timeout=None)
        self.code = code
        self.user_id = user_id

    @discord.ui.button(label="✅ Aprovar", style=discord.ButtonStyle.success, custom_id="approve_license")
    async def approve_callback(self, interaction: discord.Interaction, button: Button):
        try:
            update_key_status(self.user_id, self.code)
            role_id = 1393321539520299009  # ID da role de serviço
            user_id = get_user_id_by_key(self.code)
            
            user = interaction.guild.get_member(user_id) or await interaction.guild.fetch_member(user_id)
            await give_role(user, role_id)
            await user.send(f"✅ A tua licença `{self.code}` foi aprovada! Bem-vindo!")

            await interaction.response.send_message("✅ Licença aprovada e role atribuída.", ephemeral=True)
            await interaction.message.edit(content="🟢 Licença aprovada", view=None)
        except Exception as e:
            logger.error(f"Erro ao aprovar licença: {e}")
            await interaction.response.send_message("❌ Erro ao aprovar licença.", ephemeral=True)

    @discord.ui.button(label="❌ Rejeitar", style=discord.ButtonStyle.danger, custom_id="reject_license")
    async def reject_callback(self, interaction: discord.Interaction, button: Button):
        try:
            user = await interaction.client.fetch_user(self.user_id)
            await user.send(f"❌ A tua licença `{self.code}` foi rejeitada. Contacta o suporte se achares que é um erro.")
            await interaction.response.send_message("❌ Licença rejeitada.", ephemeral=True)
            await interaction.message.edit(content="🔴 Licença rejeitada", view=None)
        except Exception as e:
            logger.error(f"Erro ao rejeitar licença: {e}")
            await interaction.response.send_message("❌ Erro ao rejeitar licença.", ephemeral=True)

async def send_license_to_approval(interaction ,code, user_id):

    try:
        channel = interaction.guild.get_channel(1393320651611181177)
                
        if not channel:
            logger.error("Canal de aprovação não encontrado.")
            return

        embed = discord.Embed(
            title="🔑 Nova license key para aprovação",
            color=discord.Color.orange(),
            timestamp=datetime.utcnow()
        )
        embed.add_field(name="User ID", value=f"||`{user_id}`||", inline=True)
        embed.add_field(name="License key", value=f"||{code}||", inline=False)
        embed.set_footer(text="Sistema de licenças | Powered by NoLife Dev Team")

        view = LicenseApprovalView(code, user_id)
        await channel.send(embed=embed, view=view)
        logger.info(f"Pedido de aprovação enviado por ({user_id})")

    except Exception as e:
        logger.error(f"Erro ao enviar licença para aprovação: {e}")

async def handle_send_code(interaction: discord.Interaction, cooldowns: dict):
    user_id = interaction.user.id

    # Verificar se o usuário já tem uma key válida
    if user_already_has_key(user_id):
        await interaction.response.send_message("❌ Já tens uma license key.",ephemeral=True)
        return

    try:
        code = generate_secure_code(user_id)
        embed = discord.Embed(
            title="License key",
            description="A tua license key privada #NoLife.",
            color=discord.Color.light_embed()
        )
        embed.add_field(name="License key:", value=f"||{code}||")
        embed.set_footer(text="License key system | Powered by NoLife Dev Team", icon_url="https://cdn.discordapp.com/attachments/1352771477845315685/1352791135730536548/e5b4a8673da2b6cf452368c17dad4fc5.jpg")
        await send_license_to_approval(interaction,code,user_id)
        await interaction.user.send(embed=embed)
        await interaction.response.send_message("📩 License key enviada para as tuas DMs!", ephemeral=True)
        
    except discord.Forbidden:
        await interaction.response.send_message("❌ Ativa as DMs para receberes o código!", ephemeral=True)

class VerificationView(View):
    def __init__(self):
        super().__init__(timeout=None)
        self.cooldowns_verification = {}

    @discord.ui.button(label="📲Receber license key", style=discord.ButtonStyle.grey, custom_id="send_code")
    async def send_code_callback(self, interaction: discord.Interaction, button: Button):
        await handle_send_code(interaction, self.cooldowns_verification)

    @discord.ui.button(label="❔Ajuda", style=discord.ButtonStyle.blurple, custom_id="suport")
    async def suport_callback(self, interaction: discord.Interaction, button: Button):
        await interaction.response.send_modal(suportQuest())

    @discord.ui.button(label="🔌Reset key", style=discord.ButtonStyle.red, custom_id="reset_key_button")
    async def reset_key_callback(self, interaction: discord.Interaction, button: Button):
        await interaction.response.send_modal(resetQuest())

    @discord.ui.button(label="📟Verificar", style=discord.ButtonStyle.success, custom_id="verify_button")
    async def verify_callback(self, interaction: discord.Interaction, button: Button):
        await interaction.response.send_modal(verifyQuest())

class LicenceKeys(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_ready(self):
        await self.bot.wait_until_ready()
        channel = self.bot.get_channel(1393320629264056470)
        
        if channel:
            await channel.purge()
            embed = discord.Embed(
                title="License key system",
                description="Verify your key to gain acess to our product.",
                color=discord.Color.light_embed()
            )
            embed.set_footer(text="License key system | Powered by NoLife Dev Team", icon_url="https://cdn.discordapp.com/attachments/1352771477845315685/1352791135730536548/e5b4a8673da2b6cf452368c17dad4fc5.jpg")
            
            await channel.send(embed=embed, view=VerificationView())
            self.bot.add_view(VerificationView())
        else:
            logger.error(f"Canal de verificação não encontrado!")

async def setup(bot):
    await bot.add_cog(LicenceKeys(bot))